version: "3.8"

services:
  api:
    build:
      target: development
    volumes:
      - .:/app:delegated
      - deno-cache:/deno-dir/deps
    environment:
      - DENO_ENV=development
      - LOG_LEVEL=debug
    command: ["deno", "task", "start:api:dev"]

  content-processor:
    build:
      target: development
    volumes:
      - .:/app:delegated
      - deno-cache:/deno-dir/deps
    environment:
      - DENO_ENV=development
      - LOG_LEVEL=debug
    command: ["deno", "task", "start:processor:dev"]

  drizzle-studio:
    image: node:18-slim
    ports:
      - "4983:4983"
    volumes:
      - .:/app:delegated
    working_dir: /app/packages/db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: >
      sh -c "
        npm i drizzle-kit drizzle-orm
        echo '============================================================' &&
        echo '🚀 ACCESS DRIZZLE STUDIO HERE:' &&
        echo '⭐ https://local.drizzle.studio?port=4983' &&
        echo '❌ IGNORE the URL that will be output by Drizzle Kit below!' &&
        echo '============================================================\n' &&
        cd /app/packages/db &&
        npx drizzle-kit studio --verbose --host 0.0.0.0 --port 4983 --config ./drizzle/drizzle-env.js
      "
    depends_on:
      - db

  db:
    ports:
      - "5432:5432"

  auth:
    command: ["kratos", "serve", "-c", "/etc/config/kratos/kratos.yml", "--watch-courier", "--dev"]
    environment:
      - LOG_LEVEL=trace

  auth-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.3.1
    environment:
      - KRATOS_PUBLIC_URL=http://auth:4433/
      - KRATOS_BROWSER_URL=${APP_URL}/auth
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - PORT=3000
      - SECURITY_MODE=standalone
      - BASE_URL=/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-ui.rule=PathPrefix(`/`)"
      - "traefik.http.routers.auth-ui.priority=1"
      - "traefik.http.routers.auth-ui.entrypoints=web"
      - "traefik.http.services.auth-ui.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.auth-ui-headers.headers.customresponseheaders.Content-Type=text/css; charset=utf-8"
      - "traefik.http.routers.auth-ui-static.rule=PathPrefix(`/`) && Path(`/auth-layout.css`)"
      - "traefik.http.routers.auth-ui-static.priority=100"
      - "traefik.http.routers.auth-ui-static.middlewares=auth-ui-headers"
      - "traefik.http.middlewares.auth-ui-stripprefix.stripprefix.prefixes=/ui"
      - "traefik.http.routers.auth-ui.middlewares=auth-ui-stripprefix@docker"

  auth-admin-ui:
    image: ghcr.io/dfoxg/kratos-admin-ui:v2.5.0
    ports:
      - '${AUTH_ADMIN_UI_PORT:-8080}:8080'
    restart: unless-stopped
    environment:
      - KRATOS_ADMIN_URL=http://auth:4434
      - KRATOS_PUBLIC_URL=${APP_URL}/auth

  dragonfly:
    ports:
      - "6379:6379"
