version: "3.8"

services:
  api:
    build:
      target: development
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app:delegated
      - deno-cache:/deno-dir/deps
    environment:
      - DENO_ENV=development
      - LOG_LEVEL=debug
    command: ["deno", "task", "start:api"]

  content-processor:
    build:
      target: development
    volumes:
      - .:/app:delegated
      - deno-cache:/deno-dir/deps
    environment:
      - DENO_ENV=development
      - LOG_LEVEL=debug
    command: ["deno", "task", "start:processor"]

  drizzle-studio:
    image: node:18-slim
    ports:
      - "4983:4983"
    volumes:
      - .:/app:delegated
    working_dir: /app/packages/infra
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: >
      sh -c "
        echo '============================================================' &&
        echo '🚀 ACCESS DRIZZLE STUDIO HERE:' &&
        echo '⭐ https://local.drizzle.studio?port=4983' &&
        echo '❌ IGNORE the URL that will be output by Drizzle Kit below!' &&
        echo '============================================================\n' &&
        cd /app/packages/infra &&
        npx drizzle-kit studio --verbose --host 0.0.0.0 --port 4983 --config ./db/drizzle/drizzle-env.js
      "
    depends_on:
      - db

  db:
    ports:
      - "5432:5432"

  dragonfly:
    ports:
      - "6379:6379"
