version: "3.8"

services:
  api:
    build:
      target: development
    volumes:
      - .:/app:delegated
      - deno-cache:/deno-dir/deps
    environment:
      - DENO_ENV=development
      - LOG_LEVEL=debug
    command: ["deno", "task", "start:api:dev"]

  content-processor:
    build:
      target: development
    volumes:
      - .:/app:delegated
      - deno-cache:/deno-dir/deps
    environment:
      - DENO_ENV=development
      - LOG_LEVEL=debug
    command: ["deno", "task", "start:processor:dev"]

  client:
    build:
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/client:/app
      - client-node-modules:/app/node_modules

  drizzle-studio:
    image: node:18-slim
    ports:
      - "4983:4983"
    volumes:
      - .:/app:delegated
    working_dir: /app/packages/db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: >
      sh -c "
        echo '============================================================' &&
        echo '🚀 ACCESS DRIZZLE STUDIO HERE:' &&
        echo '⭐ https://local.drizzle.studio?port=4983' &&
        echo '❌ IGNORE the URL that will be output by Drizzle Kit below!' &&
        echo '============================================================\n' &&
        cd /app/packages/db &&
        npx drizzle-kit studio --verbose --host 0.0.0.0 --port 4983 --config ./drizzle/drizzle-env.js
      "
    depends_on:
      - db

  db:
    ports:
      - "5432:5432"

  auth:
    command: ["kratos", "serve", "-c", "/etc/config/kratos/kratos.yml", "--watch-courier", "--dev"]
    environment:
      - LOG_LEVEL=trace

  auth-admin-ui:
    image: ghcr.io/dfoxg/kratos-admin-ui:v2.5.0
    ports:
      - '${AUTH_ADMIN_UI_PORT:-8080}:8080'
    environment:
      - KRATOS_ADMIN_URL=http://auth:4434
      - KRATOS_PUBLIC_URL=${APP_URL}/auth

  dragonfly:
    ports:
      - "6379:6379"

volumes:
  deno-cache:
  client-node-modules:
