version: "3.8"

services:
  api:
    build:
      target: development
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app:delegated
      - deno-cache:/deno-dir/deps
    environment:
      - DENO_ENV=development
      - LOG_LEVEL=debug
    command: ["deno", "task", "start:api"]

  content-processor:
    build:
      target: development
    volumes:
      - .:/app:delegated
      - deno-cache:/deno-dir/deps
    environment:
      - DENO_ENV=development
      - LOG_LEVEL=debug
    command: ["deno", "task", "start:processor"]

  drizzle-studio:
    image: node:18-slim
    ports:
      - "4983:4983"
    volumes:
      - .:/app:delegated
    working_dir: /app/packages/infra
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: >
      sh -c "
        echo '============================================================' &&
        echo '🚀 ACCESS DRIZZLE STUDIO HERE:' &&
        echo '⭐ https://local.drizzle.studio?port=4983' &&
        echo '❌ IGNORE the URL that will be output by Drizzle Kit below!' &&
        echo '============================================================\n' &&
        cd /app/packages/infra &&
        npx drizzle-kit studio --verbose --host 0.0.0.0 --port 4983 --config ./db/drizzle/drizzle-env.js
      "
    depends_on:
      - db

  db:
    ports:
      - "5432:5432"

  auth:
    command: ["kratos", "serve", "-c", "/etc/config/kratos/kratos.yml", "--watch-courier", "--dev"]
    environment:
      - LOG_LEVEL=trace

  auth-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.3.1
    ports:
      - "${AUTH_UI_PORT}:3000"
    environment:
      - KRATOS_PUBLIC_URL=http://auth:${AUTH_PUBLIC_PORT}/
      - KRATOS_BROWSER_URL=${AUTH_PUBLIC_URL}
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - SECURITY_MODE=

  auth-admin-ui:
    image: ghcr.io/dfoxg/kratos-admin-ui:v2.5.0
    ports:
      - '${AUTH_ADMIN_UI_PORT:-8080}:8080'
    restart: unless-stopped
    environment:
      - KRATOS_ADMIN_URL=${AUTH_ADMIN_URL}
      - KRATOS_PUBLIC_URL=${AUTH_PUBLIC_URL}

  dragonfly:
    ports:
      - "6379:6379"
