export const USECASES_TOKENS = {
  Collection: {
    CollectionService: "services.collection-service",
    SpecialCollectionService: "services.special-collection-service",
    ItemManagementService: "services.item-management-service",
    CreateCollectionUseCase: "usecases.create-collection-usecase",
    GetCollectionUseCase: "usecases.get-collection-usecase",
    UpdateCollectionUseCase: "usecases.update-collection-usecase",
    DeleteCollectionUseCase: "usecases.delete-collection-usecase",
    ListCollectionsUseCase: "usecases.list-collections-usecase",
    GetItemsInCollectionUseCase: "usecases.get-items-in-collection-usecase",
    AddToCollectionUseCase: "usecases.add-to-collection-usecase",
    RemoveFromCollectionUseCase: "usecases.remove-from-collection-usecase",
    MoveItemUseCase: "usecases.move-item-usecase",
    ArchiveItemUseCase: "usecases.archive-item-usecase",
    BulkArchiveUseCase: "usecases.bulk-archive-usecase",
  },
  Item: {
    ItemService: "services.item-service",
    SaveItemUseCase: "usecases.save-item-usecase",
    GetItemUseCase: "usecases.get-item-usecase",
    UpdateItemUseCase: "usecases.update-item-usecase",
    DeleteItemUseCase: "usecases.delete-item-usecase",
    BulkDeleteItemsUseCase: "usecases.bulk-delete-items-usecase",
    ListItemsUseCase: "usecases.list-items-usecase",
    UpdateReadingProgressUseCase: "usecases.update-reading-progress-usecase",
  },
  Tag: {
    TagService: "services.tag-service",
    SaveTagUseCase: "usecases.save-tag-usecase",
    GetTagUseCase: "usecases.get-tag-usecase",
    UpdateTagUseCase: "usecases.update-tag-usecase",
    DeleteTagUseCase: "usecases.delete-tag-usecase",
    ListItemUseCase: "usecases.list-item-usecase",
    MergeTagsUseCase: "usecases.merge-tags-usecase",
    TagItemUseCase: "usecases.tag-item-usecase",
    BulkTagUseCase: "usecases.bulk-tag-usecase",
  },
  Highlight: {
    HighlightService: "services.highlight-service",
    CreateHighlightUseCase: "usecases.create-highlight-usecase",
    GetHighlightUseCase: "usecases.get-highlight-usecase",
    UpdateHighlightUseCase: "usecases.update-highlight-usecase",
    DeleteHighlightUseCase: "usecases.delete-highlight-usecase",
    BulkDeleteHighlightsUseCase: "usecases.bulk-delete-highlights-usecase",
    ListHighlightsUseCase: "usecases.list-highlights-usecase",
  },
  User: {
    UserService: "services.user-service",
    CreateUserUseCase: "usecases.create-user-usecase",
    DeleteUserUseCase: "usecases.delete-user-usecase",
    GetUserUseCase: "usecases.get-user-usecase",
    UpdateUserUseCase: "usecases.update-user-usecase",
    ListUsersUseCase: "usecases.list-users-usecase",
  },
} as const;
